// ═══════════════════════════════════════════════════════════════════════════
// create-component / archetype-builders.figma.js
// ═══════════════════════════════════════════════════════════════════════════
// Shared draw helpers + 7 archetype builders used by `draw-engine.figma.js §6.2a`
// (Archetype dispatch). Agents running `create-component` must Read this
// file in full and inline it VERBATIM inside their `use_figma` script
// between `draw-engine.figma.js §5.6` (DEFAULT_ICON_COMPONENT resolution)
// and `draw-engine.figma.js §6.0` (clear page).
//
// The extraction exists because SKILL.md grew past the context-window
// slice that agents typically inline — builders below `buildVariant` were
// being truncated, causing Inputs / Cards / Menu items to fall through
// to the 'chip' fallback in `draw-engine.figma.js §6.2a` and render incorrectly.
//
// DO NOT edit this file per component. The ONLY per-component knob is
// the `CONFIG` object defined at SKILL.md §0. Every builder reads its
// archetype sub-object (`CONFIG.surface`, `CONFIG.field`, `CONFIG.row`,
// `CONFIG.tiny`, `CONFIG.container`, `CONFIG.control`) from that CONFIG.
//
// Dependencies provided by the `draw-engine.figma.js` scaffold ABOVE the
// insertion point (do not re-declare them):
//
//   CONFIG                         — Step 0 component config
//   REGISTRY_COMPONENTS            — Step 5.1 registry map
//   bindColor(node, var, hex, tgt) — Step 5.2 color binder
//   bindNum  (node, field, var, f) — Step 5.2 numeric binder
//   labelFont, labelFontVar        — Step 5.3 font resolver
//   allTextStyles                  — Step 5.5 published text styles
//   DEFAULT_ICON_COMPONENT         — Step 5.6 icon pack resolver
//   buildVariant(...)              — `draw-engine.figma.js §5.7` chip archetype
//
// What this file provides (hoisted to top-level, so `draw-engine.figma.js §6.2a`
// dispatch can resolve every builder by name regardless of insertion order):
//
//   makeDashedSlot(...)            — dashed placeholder frame
//   makeSampleText(...)            — text node w/ published style
//   makeIconSlotShared(...)        — icon slot honoring DEFAULT_ICON_COMPONENT
//   wireIconSwapProp(...)          — INSTANCE_SWAP property wiring
//
//   buildSurfaceStackVariant(...)  — Card, Alert, Dialog, Sheet, …
//   buildFieldVariant(...)         — Input, Textarea, Select, OTP, …
//   buildRowItemVariant(...)       — MenuItem, BreadcrumbItem, Item, …
//   buildTinyVariant(...)          — Separator, Skeleton, Progress, …
//   buildControlVariant(...)       — Checkbox, Radio, Switch
//   buildContainerVariant(...)     — Accordion, Tabs, Collapsible, …
//   buildComposedVariant(...)      — composite via CONFIG.composes
//
// ═══════════════════════════════════════════════════════════════════════════
// ⚠️  FIGMA AUTO-LAYOUT ENUM GUARDRAIL — READ BEFORE EDITING ANY BUILDER
// ═══════════════════════════════════════════════════════════════════════════
// Figma rejects the entire script if any auto-layout enum is wrong. These
// are the ONLY valid values — do not paste `'STRETCH'` into anything except
// `layoutAlign`. If you see an agent-authored or runtime-inlined variant of
// these builders setting `counterAxisAlignItems = 'STRETCH'`, FIX IT TO
// `'MIN'` and rely on child-side stretching instead.
//
//   frame.layoutMode               'NONE' | 'HORIZONTAL' | 'VERTICAL'
//   frame.primaryAxisSizingMode    'FIXED' | 'AUTO'
//   frame.counterAxisSizingMode    'FIXED' | 'AUTO'
//   frame.primaryAxisAlignItems    'MIN' | 'MAX' | 'CENTER' | 'SPACE_BETWEEN'
//   frame.counterAxisAlignItems    'MIN' | 'MAX' | 'CENTER' | 'BASELINE'
//                                  ⚠️  NO 'STRETCH' — see below for how to stretch children
//   frame.layoutAlign              'INHERIT' | 'STRETCH' | 'MIN' | 'CENTER' | 'MAX'
//                                  (parent-axis alignment OF THE CHILD; 'STRETCH' is only valid HERE)
//   frame.layoutPositioning        'AUTO' | 'ABSOLUTE'
//   frame.layoutSizingHorizontal   'HUG' | 'FILL' | 'FIXED'
//   frame.layoutSizingVertical     'HUG' | 'FILL' | 'FIXED'
//
// To stretch a child across the parent's counter axis, use EITHER:
//   (a) `child.layoutAlign = 'STRETCH'` — works when parent is auto-layout
//       and child was appended to it. This is what every builder below uses.
//   (b) `child.layoutSizingHorizontal = 'FILL'` (or 'FILL' on vertical) —
//       same effect, Figma's newer sizing API.
// NEVER set `parent.counterAxisAlignItems = 'STRETCH'` — Figma throws
// `Property "counterAxisAlignItems" failed validation` and the whole draw
// aborts.
//
// ═══════════════════════════════════════════════════════════════════════════
// SHARED DRAW HELPERS (used by every archetype below `buildVariant`)
// ═══════════════════════════════════════════════════════════════════════════
// These helpers are deliberately hoisted to top-level (not closed over a
// single archetype) so `surface-stack`, `field`, `row-item`, `tiny`,
// `control`, and `container` builders can all share the same placeholder
// visual language. Every designer-replaceable region uses `makeDashedSlot`
// so the UX is uniform — dashed outline + muted caption, ready to swap.

// Create a dashed placeholder slot with a centered caption.
// Use for content regions, footer action slots, avatar image placeholders,
// chart placeholders, etc. — anywhere a designer will drop a replacement.
function makeDashedSlot(name, {
  label = null,
  w = 200,
  h = 96,
  radius = 8,
  stretch = false,
  grow = false,
  captionFillVar = 'color/background/content-muted',
  captionFillHex = '#6b7280',
  captionSize = 12,
  borderVar = 'color/border/subtle',
  borderHex = '#e5e7eb',
  fillVar = null,
  fillHex = null,
  padX = 12,
  padY = 8,
} = {}) {
  const f = figma.createFrame();
  f.name = name;
  f.layoutMode = 'HORIZONTAL';
  f.primaryAxisSizingMode = 'FIXED';
  f.counterAxisSizingMode = 'FIXED';
  f.resize(w, h);
  f.primaryAxisAlignItems = 'CENTER';
  f.counterAxisAlignItems = 'CENTER';
  f.paddingLeft = padX;
  f.paddingRight = padX;
  f.paddingTop = padY;
  f.paddingBottom = padY;
  f.itemSpacing = 0;
  if (fillVar) bindColor(f, fillVar, fillHex ?? '#ffffff', 'fills');
  else if (fillHex) {
    const h2 = fillHex.replace('#', '');
    f.fills = [{ type: 'SOLID', color: { r: parseInt(h2.slice(0,2),16)/255, g: parseInt(h2.slice(2,4),16)/255, b: parseInt(h2.slice(4,6),16)/255 } }];
  } else {
    f.fills = [];
  }
  bindColor(f, borderVar, borderHex, 'strokes');
  f.strokeWeight = 1;
  f.dashPattern = [6, 4];
  f.cornerRadius = radius;
  if (stretch) f.layoutAlign = 'STRETCH';
  if (grow) f.layoutGrow = 1;
  if (label != null) {
    const cap = figma.createText();
    cap.fontName = { family: labelFont, style: 'Regular' };
    cap.characters = String(label);
    cap.fontSize = captionSize;
    bindColor(cap, captionFillVar, captionFillHex, 'fills');
    cap.textAutoResize = 'HEIGHT';
    f.appendChild(cap);
  }
  return f;
}

// Create a sample text node using a published text style when available.
// Used everywhere the designer sees meaningful sample copy (CardTitle,
// CardDescription, Input Label, DropdownMenuItem Title, etc).
function makeSampleText(chars, styleName, fillVar = 'color/background/content', fallbackSize = 14, weight = 'Regular') {
  const t = figma.createText();
  t.fontName = { family: labelFont, style: weight };
  t.characters = String(chars);
  const ts = styleName ? allTextStyles.find(s => s.name === styleName) : null;
  if (ts) {
    t.textStyleId = ts.id;
  } else {
    t.fontSize = fallbackSize;
    if (labelFontVar) { try { t.setBoundVariable('fontFamily', labelFontVar); } catch (_) {} }
  }
  bindColor(t, fillVar, '#0a0a0a', 'fills');
  t.textAutoResize = 'HEIGHT';
  return t;
}

// Icon slot factory reusable across archetypes. Mirrors the `makeIconSlot`
// inside `buildVariant` but is callable from any builder. Honors the
// `DEFAULT_ICON_COMPONENT` resolution (`draw-engine.figma.js §5.6`) so
// INSTANCE_SWAP wiring stays consistent across archetypes.
function makeIconSlotShared(slotName, size = 24) {
  if (DEFAULT_ICON_COMPONENT) {
    const inst = DEFAULT_ICON_COMPONENT.createInstance();
    inst.name = slotName;
    try { inst.resize(size, size); } catch (_) {}
    inst.layoutPositioning = 'AUTO';
    return inst;
  }
  const f = figma.createFrame();
  f.name          = slotName;
  f.layoutMode    = 'NONE';
  f.resize(size, size);
  f.fills         = [];
  bindColor(f, 'color/border/default', '#d4d4d8', 'strokes');
  f.strokeWeight  = 1;
  f.dashPattern   = [4, 3];
  f.cornerRadius  = 4;
  f.clipsContent  = false;
  f.layoutPositioning = 'AUTO';
  return f;
}

// Wire a INSTANCE_SWAP component property on an icon-slot instance when
// DEFAULT_ICON_COMPONENT is set. No-op for placeholder frames.
function wireIconSwapProp(comp, slotNode, propKeys, propName) {
  if (!DEFAULT_ICON_COMPONENT || !slotNode || slotNode.type !== 'INSTANCE') return;
  try {
    const swapDefault = DEFAULT_ICON_COMPONENT.id;
    const preferred = DEFAULT_ICON_COMPONENT.key
      ? [{ type: 'COMPONENT', key: DEFAULT_ICON_COMPONENT.key }]
      : undefined;
    const opts = preferred ? { preferredValues: preferred } : undefined;
    const key = comp.addComponentProperty(propName, 'INSTANCE_SWAP', swapDefault, opts);
    propKeys[propName] = key;
    slotNode.componentPropertyReferences = {
      ...(slotNode.componentPropertyReferences || {}),
      mainComponent: key,
    };
  } catch (err) {
    console.warn(`wireIconSwapProp failed for ${propName}:`, err && err.message ? err.message : err);
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: surface-stack
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Card, Alert, Alert Dialog, Dialog, Sheet, Drawer, Popover,
//              Tooltip, Hover Card, Empty
// Reference: https://ui.shadcn.com/docs/components/radix/card (Card.tsx)
//
//   Card   → flex flex-col gap-6 rounded-xl border py-6
//   Header → grid items-start gap-1.5 px-6 has-[action]:grid-cols-[1fr_auto]
//   Title  → leading-none font-semibold
//   Desc   → text-muted-foreground text-sm
//   Action → col-start-2 row-span-2 row-start-1 self-start justify-self-end
//   Content→ px-6
//   Footer → flex items-center px-6
//   size=sm→ gap-4 py-4
function buildSurfaceStackVariant(name, fillVar, fallbackFill, {
  labelVar      = 'color/background/content',
  strokeVar     = 'color/border/subtle',
  radiusVar     = 'radius/xl',
  padH          = 'space/2xl',
  sizeKey       = null,
  propLabelText = 'Card',
} = {}) {
  const surface = CONFIG.surface || {};
  const padYTok = surface.sectionPadY ?? padH;
  const gapTok  = surface.gap ?? padH;
  const innerGapTok = surface.innerGap ?? 'space/xs';
  const width   = surface.width ?? 420;

  const c = figma.createComponent();
  c.name = name;
  c.layoutMode = 'VERTICAL';
  c.primaryAxisSizingMode = 'AUTO';
  c.counterAxisSizingMode = 'FIXED';
  c.resize(width, 1);
  c.primaryAxisAlignItems = 'MIN';
  c.counterAxisAlignItems = 'MIN';
  c.paddingLeft = 0;
  c.paddingRight = 0;
  bindNum(c, 'paddingTop',    padYTok, 24);
  bindNum(c, 'paddingBottom', padYTok, 24);
  bindNum(c, 'itemSpacing',   gapTok,  24);
  ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
    .forEach(fn => bindNum(c, fn, radiusVar, 12));
  bindColor(c, fillVar, fallbackFill, 'fills');
  if (strokeVar) { bindColor(c, strokeVar, '#e5e7eb', 'strokes'); c.strokeWeight = 1; }

  const titleText = typeof surface.titleText === 'function'
    ? (surface.titleText(sizeKey, null) ?? CONFIG.title)
    : (surface.titleText ?? CONFIG.title);
  const descText = typeof surface.descriptionText === 'function'
    ? surface.descriptionText(sizeKey, null)
    : (surface.descriptionText ?? CONFIG.summary?.split('.')[0] ?? null);

  const header = figma.createFrame();
  header.name = 'CardHeader';
  header.layoutMode = 'HORIZONTAL';
  header.primaryAxisSizingMode = 'FIXED';
  header.counterAxisSizingMode = 'AUTO';
  header.layoutAlign = 'STRETCH';
  header.counterAxisAlignItems = 'MIN';
  bindNum(header, 'paddingLeft',  padH, 24);
  bindNum(header, 'paddingRight', padH, 24);
  header.itemSpacing = 16;
  header.fills = [];

  const titleStack = figma.createFrame();
  titleStack.name = 'CardHeader/title-stack';
  titleStack.layoutMode = 'VERTICAL';
  titleStack.primaryAxisSizingMode = 'AUTO';
  titleStack.counterAxisSizingMode = 'AUTO';
  titleStack.layoutGrow = 1;
  bindNum(titleStack, 'itemSpacing', innerGapTok, 6);
  titleStack.fills = [];

  const titleNode = makeSampleText(titleText, surface.titleStyleName ?? 'Label/LG', labelVar, 18, 'Medium');
  titleNode.name = 'CardTitle';
  titleStack.appendChild(titleNode);

  let descNode = null;
  if (descText) {
    descNode = makeSampleText(descText, surface.descriptionStyleName ?? 'Label/SM', 'color/background/content-muted', 14);
    descNode.name = 'CardDescription';
    titleStack.appendChild(descNode);
  }
  header.appendChild(titleStack);

  let actionSlot = null;
  const actionSpec = surface.actionSlot;
  if (actionSpec && actionSpec.enabled) {
    actionSlot = makeDashedSlot('CardAction', {
      label: actionSpec.slotLabel ?? 'Action',
      w: actionSpec.width ?? 80,
      h: actionSpec.height ?? 32,
      radius: 6,
    });
    header.appendChild(actionSlot);
  }
  c.appendChild(header);

  let contentFrame = null;
  let contentSlotNode = null;
  const contentSpec = surface.contentSlot ?? { enabled: true, slotLabel: 'Content', minHeight: 96 };
  if (contentSpec.enabled !== false) {
    contentFrame = figma.createFrame();
    contentFrame.name = 'CardContent';
    contentFrame.layoutMode = 'VERTICAL';
    contentFrame.primaryAxisSizingMode = 'AUTO';
    contentFrame.counterAxisSizingMode = 'FIXED';
    contentFrame.layoutAlign = 'STRETCH';
    bindNum(contentFrame, 'paddingLeft',  padH, 24);
    bindNum(contentFrame, 'paddingRight', padH, 24);
    contentFrame.itemSpacing = 8;
    contentFrame.fills = [];
    contentSlotNode = makeDashedSlot('content-slot', {
      label:     contentSpec.slotLabel ?? 'Content',
      w:         width - 48,
      h:         contentSpec.minHeight ?? 96,
      stretch:   true,
      radius:    8,
    });
    contentFrame.appendChild(contentSlotNode);
    c.appendChild(contentFrame);
  }

  let footerFrame = null;
  const footerSpec = surface.footerSlot ?? { enabled: false };
  if (footerSpec.enabled) {
    footerFrame = figma.createFrame();
    footerFrame.name = 'CardFooter';
    footerFrame.layoutMode = 'HORIZONTAL';
    footerFrame.primaryAxisSizingMode = 'FIXED';
    footerFrame.counterAxisSizingMode = 'AUTO';
    footerFrame.layoutAlign = 'STRETCH';
    const align = footerSpec.align ?? 'start';
    footerFrame.primaryAxisAlignItems = align === 'end' ? 'MAX' : align === 'between' ? 'SPACE_BETWEEN' : 'MIN';
    footerFrame.counterAxisAlignItems = 'CENTER';
    bindNum(footerFrame, 'paddingLeft',  padH, 24);
    bindNum(footerFrame, 'paddingRight', padH, 24);
    footerFrame.itemSpacing = 8;
    footerFrame.fills = [];
    const fh = footerSpec.minHeight ?? 44;
    const fLabel = footerSpec.slotLabel ?? 'Footer';
    const footerSlotNode = makeDashedSlot(`footer-slot/${fLabel.toLowerCase().replace(/\s+/g, '-')}`, {
      label: fLabel, w: 140, h: fh, radius: 6,
    });
    footerFrame.appendChild(footerSlotNode);
    c.appendChild(footerFrame);
  }

  const propKeys = {};
  const cp = CONFIG.componentProps || {};
  try {
    if (cp.title !== false) {
      propKeys.title = c.addComponentProperty('Title', 'TEXT', String(titleText));
      titleNode.componentPropertyReferences = { characters: propKeys.title };
    }
    if (descNode && cp.description !== false) {
      propKeys.description = c.addComponentProperty('Description', 'TEXT', String(descText));
      descNode.componentPropertyReferences = { characters: propKeys.description };
    }
    if (actionSlot && cp.actionSlot !== false) {
      propKeys.actionSlot = c.addComponentProperty('Show action', 'BOOLEAN', true);
      actionSlot.componentPropertyReferences = { visible: propKeys.actionSlot };
    }
    if (footerFrame && cp.footer !== false) {
      propKeys.footer = c.addComponentProperty('Show footer', 'BOOLEAN', true);
      footerFrame.componentPropertyReferences = { visible: propKeys.footer };
    }
  } catch (err) {
    console.warn(`addComponentProperty (surface-stack) failed on '${name}':`, err && err.message ? err.message : err);
  }

  figma.currentPage.appendChild(c);
  return {
    component: c,
    slots: { title: titleNode, description: descNode, action: actionSlot, content: contentSlotNode, footer: footerFrame, label: null, leading: null, trailing: null, center: null },
    propKeys,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: field
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Input, Textarea, Select, Combobox, Date Picker, Input OTP,
//              Input Group, Label, Native Select
// Reference: https://ui.shadcn.com/docs/components/radix/input (Input.tsx)
//
//   Input    → flex h-9 w-full rounded-md border bg-transparent px-3 py-1 text-sm
//   Textarea → flex min-h-[60px] w-full rounded-md border bg-transparent px-3 py-2 text-sm
//   Select   → flex h-9 w-full items-center justify-between rounded-md border bg-transparent px-3 py-2 text-sm
//   sm/lg    → h-8 text-xs / h-10 text-base (per shadcn size variants)
function buildFieldVariant(name, fillVar, fallbackFill, {
  labelVar   = 'color/background/content',
  strokeVar  = 'color/border/default',
  radiusVar  = 'radius/md',
  padH       = 'space/md',
  sizeKey    = null,
} = {}) {
  const field = CONFIG.field || {};
  const fieldType = field.fieldType ?? 'input';           // 'input' | 'textarea' | 'select' | 'otp'
  const showLabel = field.showLabel !== false;
  const labelText = field.labelText ?? 'Label';
  const placeholderText = field.placeholderText ?? (fieldType === 'select' ? 'Select an option…' : 'Placeholder');
  const showHelper = field.showHelper === true;
  const helperText = field.helperText ?? 'Helper text';
  const leadingIcon  = field.leadingIcon === true;
  const trailingIcon = field.trailingIcon === true || fieldType === 'select';  // Select always has chevron
  const fh = sizeKey === 'sm' ? 32 : sizeKey === 'lg' ? 44 : 36;
  const fontSize = sizeKey === 'sm' ? 12 : sizeKey === 'lg' ? 16 : 14;
  const labelStyleName = field.labelStyleName ?? 'Label/SM';
  const width = field.width ?? 320;

  const c = figma.createComponent();
  c.name = name;
  c.layoutMode = 'VERTICAL';
  c.primaryAxisSizingMode = 'AUTO';
  c.counterAxisSizingMode = 'FIXED';
  c.resize(width, 1);
  c.primaryAxisAlignItems = 'MIN';
  c.counterAxisAlignItems = 'MIN';
  bindNum(c, 'itemSpacing', 'space/xs', 6);
  c.fills = [];
  c.strokes = [];

  let labelNode = null;
  if (showLabel) {
    labelNode = makeSampleText(labelText, labelStyleName, labelVar, 14, 'Medium');
    labelNode.name = 'Label';
    c.appendChild(labelNode);
  }

  const fieldChrome = figma.createFrame();
  fieldChrome.name = 'field';
  fieldChrome.layoutMode = fieldType === 'textarea' ? 'VERTICAL' : 'HORIZONTAL';
  fieldChrome.primaryAxisSizingMode = fieldType === 'textarea' ? 'FIXED' : 'FIXED';
  fieldChrome.counterAxisSizingMode = 'FIXED';
  fieldChrome.layoutAlign = 'STRETCH';
  if (fieldType === 'textarea') {
    fieldChrome.resize(width, field.textareaMinHeight ?? 96);
    fieldChrome.primaryAxisAlignItems = 'MIN';
    fieldChrome.counterAxisAlignItems = 'MIN';
  } else {
    fieldChrome.resize(width, fh);
    fieldChrome.primaryAxisAlignItems = fieldType === 'select' ? 'SPACE_BETWEEN' : 'MIN';
    fieldChrome.counterAxisAlignItems = 'CENTER';
  }
  bindNum(fieldChrome, 'paddingLeft',  padH, 12);
  bindNum(fieldChrome, 'paddingRight', padH, 12);
  fieldChrome.paddingTop    = fieldType === 'textarea' ? 8 : 4;
  fieldChrome.paddingBottom = fieldType === 'textarea' ? 8 : 4;
  fieldChrome.itemSpacing = 8;
  bindColor(fieldChrome, fillVar, fallbackFill, 'fills');
  if (strokeVar) { bindColor(fieldChrome, strokeVar, '#e5e7eb', 'strokes'); fieldChrome.strokeWeight = 1; }
  ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
    .forEach(fn => bindNum(fieldChrome, fn, radiusVar, 6));

  let leadingSlotNode = null;
  if (leadingIcon) {
    leadingSlotNode = makeIconSlotShared('icon-slot/leading', 20);
    fieldChrome.appendChild(leadingSlotNode);
  }

  // OTP renders as 4-6 small boxes rather than a single field.
  let placeholder = null;
  if (fieldType === 'otp') {
    const boxCount = field.otpLength ?? 6;
    const boxW = Math.min(44, Math.floor((width - 12 * (boxCount - 1)) / boxCount));
    fieldChrome.fills = [];
    fieldChrome.strokes = [];
    fieldChrome.itemSpacing = 8;
    for (let i = 0; i < boxCount; i++) {
      const box = figma.createFrame();
      box.name = `otp-slot/${i}`;
      box.layoutMode = 'HORIZONTAL';
      box.primaryAxisSizingMode = 'FIXED';
      box.counterAxisSizingMode = 'FIXED';
      box.resize(boxW, fh);
      box.primaryAxisAlignItems = 'CENTER';
      box.counterAxisAlignItems = 'CENTER';
      bindColor(box, fillVar, fallbackFill, 'fills');
      bindColor(box, strokeVar ?? 'color/border/default', '#e5e7eb', 'strokes');
      box.strokeWeight = 1;
      ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
        .forEach(fn => bindNum(box, fn, radiusVar, 6));
      fieldChrome.appendChild(box);
    }
  } else {
    placeholder = makeSampleText(placeholderText, null, 'color/background/content-muted', fontSize);
    placeholder.name = fieldType === 'select' ? 'value' : 'placeholder';
    if (fieldType !== 'textarea') placeholder.layoutGrow = 1;
    fieldChrome.appendChild(placeholder);
  }

  let trailingSlotNode = null;
  if (trailingIcon) {
    trailingSlotNode = makeIconSlotShared(fieldType === 'select' ? 'icon-slot/chevron' : 'icon-slot/trailing', 16);
    fieldChrome.appendChild(trailingSlotNode);
  }

  c.appendChild(fieldChrome);

  let helperNode = null;
  if (showHelper) {
    helperNode = makeSampleText(helperText, 'Doc/Caption', 'color/background/content-muted', 12);
    helperNode.name = 'helper';
    c.appendChild(helperNode);
  }

  const propKeys = {};
  const cp = CONFIG.componentProps || {};
  try {
    if (labelNode && cp.label !== false) {
      propKeys.label = c.addComponentProperty('Label', 'TEXT', labelText);
      labelNode.componentPropertyReferences = { characters: propKeys.label };
    }
    if (placeholder && cp.placeholder !== false) {
      propKeys.placeholder = c.addComponentProperty('Placeholder', 'TEXT', placeholderText);
      placeholder.componentPropertyReferences = { characters: propKeys.placeholder };
    }
    if (helperNode && cp.helper !== false) {
      propKeys.helper = c.addComponentProperty('Helper', 'TEXT', helperText);
      helperNode.componentPropertyReferences = { characters: propKeys.helper };
    }
    if (leadingSlotNode) {
      propKeys.leadingIcon = c.addComponentProperty('Leading icon', 'BOOLEAN', true);
      leadingSlotNode.componentPropertyReferences = {
        ...(leadingSlotNode.componentPropertyReferences || {}),
        visible: propKeys.leadingIcon,
      };
      wireIconSwapProp(c, leadingSlotNode, propKeys, 'Icon: leading');
    }
    if (trailingSlotNode && fieldType !== 'select') {
      propKeys.trailingIcon = c.addComponentProperty('Trailing icon', 'BOOLEAN', true);
      trailingSlotNode.componentPropertyReferences = {
        ...(trailingSlotNode.componentPropertyReferences || {}),
        visible: propKeys.trailingIcon,
      };
      wireIconSwapProp(c, trailingSlotNode, propKeys, 'Icon: trailing');
    } else if (trailingSlotNode) {
      // Select chevron — INSTANCE_SWAP only, no boolean toggle.
      wireIconSwapProp(c, trailingSlotNode, propKeys, 'Icon: chevron');
    }
  } catch (err) {
    console.warn(`addComponentProperty (field) failed on '${name}':`, err && err.message ? err.message : err);
  }

  figma.currentPage.appendChild(c);
  return {
    component: c,
    slots: { label: labelNode, placeholder, helper: helperNode, leading: leadingSlotNode, trailing: trailingSlotNode, title: null, description: null, action: null, content: null, footer: null, center: null },
    propKeys,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: row-item
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Item, Dropdown Menu (MenuItem), Menubar Item, Navigation Menu
//              Item, Context Menu Item, Command Item, Breadcrumb Item,
//              Sidebar row
// Reference: https://ui.shadcn.com/docs/components/radix/dropdown-menu
//            https://ui.shadcn.com/docs/components/radix/item
//
//   MenuItem → flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm
//   Item     → lead-icon + (title + description stacked) + trail-action
function buildRowItemVariant(name, fillVar, fallbackFill, {
  labelVar   = 'color/background/content',
  strokeVar  = null,
  radiusVar  = 'radius/sm',
  padH       = 'space/sm',
  sizeKey    = null,
} = {}) {
  const row = CONFIG.row || {};
  const titleText = row.titleText ?? CONFIG.title ?? 'Item';
  const descText  = row.descriptionText ?? null;
  const showLeading  = row.leadingIcon !== false;
  const showTrailing = row.trailingIcon !== false;
  const showShortcut = row.shortcut === true;
  const shortcutText = row.shortcutText ?? '⌘K';
  const width = row.width ?? 280;

  const c = figma.createComponent();
  c.name = name;
  c.layoutMode = 'HORIZONTAL';
  c.primaryAxisSizingMode = 'FIXED';
  c.counterAxisSizingMode = 'AUTO';
  c.resize(width, 1);
  c.primaryAxisAlignItems = 'MIN';
  c.counterAxisAlignItems = 'CENTER';
  bindNum(c, 'paddingLeft',   padH, 12);
  bindNum(c, 'paddingRight',  padH, 12);
  bindNum(c, 'paddingTop',    'space/xs', 6);
  bindNum(c, 'paddingBottom', 'space/xs', 6);
  bindNum(c, 'itemSpacing',   'space/sm', 8);
  ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
    .forEach(fn => bindNum(c, fn, radiusVar, 4));
  bindColor(c, fillVar, fallbackFill, 'fills');
  if (strokeVar) { bindColor(c, strokeVar, '#e5e7eb', 'strokes'); c.strokeWeight = 1; }

  let leadingSlotNode = null;
  if (showLeading) {
    leadingSlotNode = makeIconSlotShared('icon-slot/leading', 16);
    c.appendChild(leadingSlotNode);
  }

  const textStack = figma.createFrame();
  textStack.name = 'row/text-stack';
  textStack.layoutMode = 'VERTICAL';
  textStack.primaryAxisSizingMode = 'AUTO';
  textStack.counterAxisSizingMode = 'AUTO';
  textStack.layoutGrow = 1;
  textStack.itemSpacing = 2;
  textStack.fills = [];

  const titleNode = makeSampleText(titleText, row.titleStyleName ?? 'Label/SM', labelVar, 14);
  titleNode.name = 'row/title';
  textStack.appendChild(titleNode);

  let descNode = null;
  if (descText) {
    descNode = makeSampleText(descText, row.descriptionStyleName ?? 'Doc/Caption', 'color/background/content-muted', 12);
    descNode.name = 'row/description';
    textStack.appendChild(descNode);
  }
  c.appendChild(textStack);

  let shortcutNode = null;
  if (showShortcut) {
    shortcutNode = makeSampleText(shortcutText, 'Doc/Code', 'color/background/content-muted', 12);
    shortcutNode.name = 'row/shortcut';
    c.appendChild(shortcutNode);
  }

  let trailingSlotNode = null;
  if (showTrailing) {
    trailingSlotNode = makeIconSlotShared(row.trailingIsChevron ? 'icon-slot/chevron' : 'icon-slot/trailing', 16);
    c.appendChild(trailingSlotNode);
  }

  const propKeys = {};
  const cp = CONFIG.componentProps || {};
  try {
    if (cp.title !== false) {
      propKeys.title = c.addComponentProperty('Title', 'TEXT', String(titleText));
      titleNode.componentPropertyReferences = { characters: propKeys.title };
    }
    if (descNode && cp.description !== false) {
      propKeys.description = c.addComponentProperty('Description', 'TEXT', String(descText));
      descNode.componentPropertyReferences = { characters: propKeys.description };
    }
    if (shortcutNode && cp.shortcut !== false) {
      propKeys.shortcut = c.addComponentProperty('Shortcut', 'TEXT', String(shortcutText));
      shortcutNode.componentPropertyReferences = { characters: propKeys.shortcut };
    }
    if (leadingSlotNode) {
      propKeys.leadingIcon = c.addComponentProperty('Leading icon', 'BOOLEAN', true);
      leadingSlotNode.componentPropertyReferences = {
        ...(leadingSlotNode.componentPropertyReferences || {}),
        visible: propKeys.leadingIcon,
      };
      wireIconSwapProp(c, leadingSlotNode, propKeys, 'Icon: leading');
    }
    if (trailingSlotNode) {
      propKeys.trailingIcon = c.addComponentProperty('Trailing icon', 'BOOLEAN', true);
      trailingSlotNode.componentPropertyReferences = {
        ...(trailingSlotNode.componentPropertyReferences || {}),
        visible: propKeys.trailingIcon,
      };
      wireIconSwapProp(c, trailingSlotNode, propKeys, row.trailingIsChevron ? 'Icon: chevron' : 'Icon: trailing');
    }
  } catch (err) {
    console.warn(`addComponentProperty (row-item) failed on '${name}':`, err && err.message ? err.message : err);
  }

  figma.currentPage.appendChild(c);
  return {
    component: c,
    slots: { title: titleNode, description: descNode, leading: leadingSlotNode, trailing: trailingSlotNode, shortcut: shortcutNode, label: null, action: null, content: null, footer: null, center: null },
    propKeys,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: tiny
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Separator, Skeleton, Spinner, Progress, Aspect Ratio, Avatar,
//              Scroll Area
// Reference: https://ui.shadcn.com/docs/components/radix/separator
//            https://ui.shadcn.com/docs/components/radix/skeleton
//            https://ui.shadcn.com/docs/components/radix/avatar
//            https://ui.shadcn.com/docs/components/radix/progress
//
// Dispatches on CONFIG.tiny.shape to render the canonical primitive.
function buildTinyVariant(name, fillVar, fallbackFill, {
  labelVar   = 'color/background/content',
  strokeVar  = null,
  radiusVar  = 'radius/full',
  padH       = 'space/none',
  sizeKey    = null,
} = {}) {
  const tiny = CONFIG.tiny || {};
  const shape = tiny.shape ?? 'skeleton';
  const orientation = tiny.orientation ?? 'horizontal';

  if (shape === 'separator') {
    const w = tiny.width ?? (orientation === 'vertical' ? 1 : 240);
    const h = tiny.height ?? (orientation === 'vertical' ? 120 : 1);
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'NONE';
    c.resize(w, h);
    bindColor(c, strokeVar ?? 'color/border/default', '#e5e7eb', 'fills');
    figma.currentPage.appendChild(c);
    return { component: c, slots: {}, propKeys: {} };
  }

  if (shape === 'skeleton') {
    const w = tiny.width ?? 200;
    const h = tiny.height ?? 16;
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'NONE';
    c.resize(w, h);
    bindColor(c, fillVar ?? 'color/background/variant', fallbackFill ?? '#f4f4f5', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(c, fn, 'radius/md', 6));
    figma.currentPage.appendChild(c);
    return { component: c, slots: {}, propKeys: {} };
  }

  if (shape === 'spinner') {
    const sz = tiny.size ?? 24;
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'NONE';
    c.resize(sz, sz);
    c.fills = [];
    bindColor(c, strokeVar ?? 'color/border/default', '#d4d4d8', 'strokes');
    c.strokeWeight = 2;
    c.cornerRadius = sz / 2;
    figma.currentPage.appendChild(c);
    return { component: c, slots: {}, propKeys: {} };
  }

  if (shape === 'progress') {
    const w = tiny.width ?? 280;
    const h = tiny.height ?? 8;
    const filled = Math.max(0, Math.min(1, tiny.filled ?? 0.4));
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'HORIZONTAL';
    c.primaryAxisSizingMode = 'FIXED';
    c.counterAxisSizingMode = 'FIXED';
    c.resize(w, h);
    c.primaryAxisAlignItems = 'MIN';
    c.counterAxisAlignItems = 'CENTER';
    bindColor(c, 'color/background/variant', '#f4f4f5', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(c, fn, 'radius/full', h / 2));
    const bar = figma.createFrame();
    bar.name = 'progress/bar';
    bar.resize(Math.max(1, Math.floor(w * filled)), h);
    bar.layoutPositioning = 'AUTO';
    bindColor(bar, fillVar ?? 'color/primary/default', fallbackFill ?? '#1a1a1a', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(bar, fn, 'radius/full', h / 2));
    c.appendChild(bar);
    figma.currentPage.appendChild(c);
    return { component: c, slots: { bar }, propKeys: {} };
  }

  if (shape === 'avatar') {
    const sz = tiny.size ?? 40;
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'HORIZONTAL';
    c.primaryAxisSizingMode = 'FIXED';
    c.counterAxisSizingMode = 'FIXED';
    c.resize(sz, sz);
    c.primaryAxisAlignItems = 'CENTER';
    c.counterAxisAlignItems = 'CENTER';
    c.clipsContent = true;
    bindColor(c, fillVar ?? 'color/background/variant', fallbackFill ?? '#e5e7eb', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(c, fn, 'radius/full', sz / 2));
    const initials = makeSampleText(tiny.initials ?? 'AB', null, 'color/background/content-muted', Math.round(sz * 0.4), 'Medium');
    initials.name = 'avatar/initials';
    c.appendChild(initials);
    figma.currentPage.appendChild(c);
    return { component: c, slots: { initials }, propKeys: {} };
  }

  if (shape === 'aspect-ratio' || shape === 'scroll-area') {
    const w = tiny.width ?? 320;
    const h = tiny.height ?? (shape === 'aspect-ratio' ? 180 : 200);
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'HORIZONTAL';
    c.primaryAxisSizingMode = 'FIXED';
    c.counterAxisSizingMode = 'FIXED';
    c.resize(w, h);
    c.primaryAxisAlignItems = 'CENTER';
    c.counterAxisAlignItems = 'CENTER';
    c.fills = [];
    bindColor(c, strokeVar ?? 'color/border/subtle', '#e5e7eb', 'strokes');
    c.strokeWeight = 1;
    c.dashPattern = [6, 4];
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(c, fn, 'radius/md', 6));
    const cap = makeSampleText(shape === 'aspect-ratio' ? 'Aspect ratio' : 'Scroll area', null, 'color/background/content-muted', 12);
    c.appendChild(cap);
    figma.currentPage.appendChild(c);
    return { component: c, slots: {}, propKeys: {} };
  }

  throw new Error(`buildTinyVariant: unknown CONFIG.tiny.shape '${shape}' for '${name}'. Expected one of: separator, skeleton, spinner, progress, avatar, aspect-ratio, scroll-area.`);
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: control
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Checkbox, Radio Group item, Switch
// Reference: https://ui.shadcn.com/docs/components/radix/checkbox
//            https://ui.shadcn.com/docs/components/radix/radio-group
//            https://ui.shadcn.com/docs/components/radix/switch
//
//   Checkbox → h-4 w-4 rounded-sm border border-primary
//   Radio    → h-4 w-4 rounded-full border border-primary
//   Switch   → h-6 w-11 rounded-full border + inner thumb
//
// Control variants use cva-driven variant-property-level checked state
// (see CONVENTIONS §13.1 — checked IS a figma variant for controls).
function buildControlVariant(name, fillVar, fallbackFill, {
  labelVar  = 'color/background/content',
  strokeVar = 'color/border/default',
  radiusVar = 'radius/sm',
  padH      = 'space/none',
  sizeKey   = null,
} = {}) {
  const control = CONFIG.control || {};
  const shape = control.shape ?? 'checkbox';
  const sz = control.size ?? 16;
  const checked = /checked=true|pressed=true|on/.test(name);

  if (shape === 'switch') {
    const w = control.width ?? 36;
    const h = control.height ?? 20;
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'HORIZONTAL';
    c.primaryAxisSizingMode = 'FIXED';
    c.counterAxisSizingMode = 'FIXED';
    c.resize(w, h);
    c.primaryAxisAlignItems = checked ? 'MAX' : 'MIN';
    c.counterAxisAlignItems = 'CENTER';
    c.paddingLeft = 2; c.paddingRight = 2;
    bindColor(c, checked ? (control.trackOnVar ?? 'color/primary/default') : (control.trackOffVar ?? 'color/background/variant'), checked ? '#1a1a1a' : '#e5e7eb', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(c, fn, 'radius/full', h / 2));
    const thumb = figma.createFrame();
    thumb.name = 'switch/thumb';
    thumb.resize(h - 4, h - 4);
    bindColor(thumb, control.thumbVar ?? 'color/background/default', '#ffffff', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(thumb, fn, 'radius/full', (h - 4) / 2));
    c.appendChild(thumb);
    figma.currentPage.appendChild(c);
    return { component: c, slots: { thumb }, propKeys: {} };
  }

  // checkbox / radio
  const c = figma.createComponent();
  c.name = name;
  c.layoutMode = 'HORIZONTAL';
  c.primaryAxisSizingMode = 'FIXED';
  c.counterAxisSizingMode = 'FIXED';
  c.resize(sz, sz);
  c.primaryAxisAlignItems = 'CENTER';
  c.counterAxisAlignItems = 'CENTER';
  const cornerTok = shape === 'radio' ? 'radius/full' : radiusVar;
  const cornerFallback = shape === 'radio' ? sz / 2 : 3;
  if (checked) {
    bindColor(c, fillVar ?? 'color/primary/default', fallbackFill ?? '#1a1a1a', 'fills');
  } else {
    c.fills = [];
  }
  bindColor(c, strokeVar, '#d4d4d8', 'strokes');
  c.strokeWeight = 1;
  ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
    .forEach(fn => bindNum(c, fn, cornerTok, cornerFallback));

  if (checked) {
    if (shape === 'radio') {
      const dot = figma.createFrame();
      dot.name = 'radio/dot';
      const dotSz = Math.round(sz * 0.5);
      dot.resize(dotSz, dotSz);
      bindColor(dot, control.indicatorVar ?? 'color/primary/content', '#ffffff', 'fills');
      ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
        .forEach(fn => bindNum(dot, fn, 'radius/full', dotSz / 2));
      c.appendChild(dot);
    } else {
      const check = makeSampleText('✓', null, control.indicatorVar ?? 'color/primary/content', Math.round(sz * 0.7), 'Medium');
      check.name = 'checkbox/check';
      c.appendChild(check);
    }
  }
  figma.currentPage.appendChild(c);
  return { component: c, slots: {}, propKeys: {} };
}

// ═══════════════════════════════════════════════════════════════════════════
// ARCHETYPE: container
// ═══════════════════════════════════════════════════════════════════════════
// Shipped for: Accordion, Collapsible, Tabs, Resizable
// Reference: https://ui.shadcn.com/docs/components/radix/accordion
//            https://ui.shadcn.com/docs/components/radix/tabs
//
//   Accordion item → header row with title + chevron, divider, expandable
//                    content panel below (dashed slot when open)
//   Tabs           → TabsList row (padded, rounded, muted bg) with
//                    TabsTriggers + TabsContent dashed slot below
function buildContainerVariant(name, fillVar, fallbackFill, {
  labelVar   = 'color/background/content',
  strokeVar  = 'color/border/subtle',
  radiusVar  = 'radius/md',
  padH       = 'space/md',
  sizeKey    = null,
} = {}) {
  const container = CONFIG.container || {};
  const kind = container.kind ?? 'accordion';  // 'accordion' | 'tabs'
  const expanded = /open=true|expanded=true|active=true|state=open/.test(name);
  const width = container.width ?? 360;

  if (kind === 'tabs') {
    const tabs = container.tabs ?? ['Account', 'Password', 'Notifications'];
    const activeIdx = container.activeIndex ?? 0;
    const c = figma.createComponent();
    c.name = name;
    c.layoutMode = 'VERTICAL';
    c.primaryAxisSizingMode = 'AUTO';
    c.counterAxisSizingMode = 'FIXED';
    c.resize(width, 1);
    c.primaryAxisAlignItems = 'MIN';
    c.counterAxisAlignItems = 'MIN';
    c.itemSpacing = 12;
    c.fills = [];

    const list = figma.createFrame();
    list.name = 'TabsList';
    list.layoutMode = 'HORIZONTAL';
    list.primaryAxisSizingMode = 'AUTO';
    list.counterAxisSizingMode = 'AUTO';
    list.primaryAxisAlignItems = 'MIN';
    list.counterAxisAlignItems = 'CENTER';
    list.paddingLeft = 4; list.paddingRight = 4;
    list.paddingTop = 4;  list.paddingBottom = 4;
    list.itemSpacing = 4;
    bindColor(list, 'color/background/variant', '#f4f4f5', 'fills');
    ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
      .forEach(fn => bindNum(list, fn, radiusVar, 6));
    tabs.forEach((t, i) => {
      const trigger = figma.createFrame();
      trigger.name = `TabsTrigger/${t.toLowerCase()}`;
      trigger.layoutMode = 'HORIZONTAL';
      trigger.primaryAxisSizingMode = 'AUTO';
      trigger.counterAxisSizingMode = 'AUTO';
      trigger.paddingLeft = 12; trigger.paddingRight = 12;
      trigger.paddingTop = 6;   trigger.paddingBottom = 6;
      trigger.primaryAxisAlignItems = 'CENTER';
      trigger.counterAxisAlignItems = 'CENTER';
      if (i === activeIdx) {
        bindColor(trigger, 'color/background/default', '#ffffff', 'fills');
      } else {
        trigger.fills = [];
      }
      ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']
        .forEach(fn => bindNum(trigger, fn, radiusVar, 6));
      const lbl = makeSampleText(t, 'Label/SM', i === activeIdx ? labelVar : 'color/background/content-muted', 14, i === activeIdx ? 'Medium' : 'Regular');
      trigger.appendChild(lbl);
      list.appendChild(trigger);
    });
    c.appendChild(list);

    const panel = makeDashedSlot('TabsContent', {
      label: `${tabs[activeIdx]} content`,
      w: width,
      h: container.panelMinHeight ?? 120,
      stretch: true,
      radius: 8,
    });
    c.appendChild(panel);
    figma.currentPage.appendChild(c);
    return { component: c, slots: { list, panel }, propKeys: {} };
  }

  // accordion item
  const titleText = container.titleText ?? 'Is it accessible?';
  const panelText = container.panelText ?? 'Yes. It adheres to the WAI-ARIA design pattern.';
  const c = figma.createComponent();
  c.name = name;
  c.layoutMode = 'VERTICAL';
  c.primaryAxisSizingMode = 'AUTO';
  c.counterAxisSizingMode = 'FIXED';
  c.resize(width, 1);
  c.primaryAxisAlignItems = 'MIN';
  c.counterAxisAlignItems = 'MIN';
  c.itemSpacing = 0;
  c.fills = [];
  bindColor(c, strokeVar, '#e5e7eb', 'strokes');
  c.strokeWeight = 0;
  c.strokeTopWeight = 0; c.strokeRightWeight = 0; c.strokeLeftWeight = 0; c.strokeBottomWeight = 1;

  const trigger = figma.createFrame();
  trigger.name = 'AccordionTrigger';
  trigger.layoutMode = 'HORIZONTAL';
  trigger.primaryAxisSizingMode = 'FIXED';
  trigger.counterAxisSizingMode = 'AUTO';
  trigger.layoutAlign = 'STRETCH';
  trigger.primaryAxisAlignItems = 'SPACE_BETWEEN';
  trigger.counterAxisAlignItems = 'CENTER';
  trigger.paddingLeft = 0; trigger.paddingRight = 0;
  trigger.paddingTop = 12; trigger.paddingBottom = 12;
  trigger.itemSpacing = 8;
  trigger.fills = [];
  const tTitle = makeSampleText(titleText, 'Label/MD', labelVar, 14, 'Medium');
  tTitle.name = 'AccordionTrigger/title';
  trigger.appendChild(tTitle);
  const chev = makeIconSlotShared('icon-slot/chevron', 16);
  trigger.appendChild(chev);
  c.appendChild(trigger);

  let panel = null;
  if (expanded) {
    panel = figma.createFrame();
    panel.name = 'AccordionContent';
    panel.layoutMode = 'VERTICAL';
    panel.primaryAxisSizingMode = 'AUTO';
    panel.counterAxisSizingMode = 'FIXED';
    panel.layoutAlign = 'STRETCH';
    panel.paddingTop = 0; panel.paddingBottom = 16;
    panel.paddingLeft = 0; panel.paddingRight = 0;
    panel.fills = [];
    const body = makeSampleText(panelText, 'Label/SM', 'color/background/content-muted', 14);
    body.name = 'AccordionContent/body';
    panel.appendChild(body);
    c.appendChild(panel);
  }

  const propKeys = {};
  const cp = CONFIG.componentProps || {};
  try {
    if (cp.title !== false) {
      propKeys.title = c.addComponentProperty('Title', 'TEXT', String(titleText));
      tTitle.componentPropertyReferences = { characters: propKeys.title };
    }
    if (panel && cp.content !== false) {
      propKeys.content = c.addComponentProperty('Content', 'TEXT', String(panelText));
      panel.children[0].componentPropertyReferences = { characters: propKeys.content };
    }
    wireIconSwapProp(c, chev, propKeys, 'Icon: chevron');
  } catch (err) {
    console.warn(`addComponentProperty (container) failed on '${name}':`, err && err.message ? err.message : err);
  }

  figma.currentPage.appendChild(c);
  return { component: c, slots: { trigger, chevron: chev, panel }, propKeys };
}

// When CONFIG.composes is non-empty, each variant is an instance stack: outer
// chrome still comes from this composite's cva (same bindColor/bindNum as
// buildVariant); inner children are real InstanceNodes of published atoms
// resolved via REGISTRY_COMPONENTS (conventions/02-archetype-routing.md §3.05).
function buildComposedVariant(name, fillVar, fallbackFill, {
  labelVar         = 'color/background/content',
  strokeVar        = null,
  radiusVar        = 'radius/md',
  padH             = 'space/md',
  padV             = 'space/xs',
} = {}) {
  const c = figma.createComponent();
  c.name = name;
  c.layoutMode            = 'HORIZONTAL';
  c.primaryAxisSizingMode = 'AUTO';
  c.counterAxisSizingMode = 'AUTO';
  c.primaryAxisAlignItems = 'CENTER';
  c.counterAxisAlignItems = 'CENTER';

  bindNum(c, 'paddingLeft',   padH,     16);
  bindNum(c, 'paddingRight',  padH,     16);
  bindNum(c, 'paddingTop',    padV,      8);
  bindNum(c, 'paddingBottom', padV,      8);
  bindNum(c, 'itemSpacing',  'space/sm', 8);
  ['topLeftRadius', 'topRightRadius', 'bottomLeftRadius', 'bottomRightRadius']
    .forEach(f => bindNum(c, f, radiusVar, 6));
  bindColor(c, fillVar, fallbackFill, 'fills');
  if (strokeVar) {
    bindColor(c, strokeVar, '#e5e7eb', 'strokes');
    c.strokeWeight = 1;
  }

  for (const spec of CONFIG.composes) {
    const slotFrame = figma.createFrame();
    slotFrame.name = `slot/${spec.slot}`;
    slotFrame.layoutMode = 'HORIZONTAL';
    slotFrame.primaryAxisSizingMode = 'AUTO';
    slotFrame.counterAxisSizingMode = 'AUTO';
    slotFrame.primaryAxisAlignItems = 'CENTER';
    slotFrame.counterAxisAlignItems = 'CENTER';
    bindNum(slotFrame, 'paddingLeft',   'space/none', 0);
    bindNum(slotFrame, 'paddingRight',  'space/none', 0);
    bindNum(slotFrame, 'paddingTop',    'space/none', 0);
    bindNum(slotFrame, 'paddingBottom', 'space/none', 0);
    bindNum(slotFrame, 'itemSpacing',  'space/sm', 8);

    const reg = REGISTRY_COMPONENTS[spec.component];
    if (!reg || !reg.nodeId) {
      throw new Error(
        `Composite '${CONFIG.component}' composes '${spec.component}' but registry is missing nodeId. ` +
          `Draw ${spec.component} first (updates .designops-registry.json), then re-run this composite.`,
      );
    }
    const main = figma.getNodeById(reg.nodeId);
    if (!main || main.type !== 'COMPONENT_SET') {
      throw new Error(
        `Registry node for '${spec.component}' must be a COMPONENT_SET (got ${main ? main.type : 'null'}).`,
      );
    }
    const n = spec.cardinality === 'many' ? (spec.count != null ? spec.count : 3) : 1;
    for (let i = 0; i < n; i++) {
      const inst = main.createInstance();
      if (spec.defaultProps && typeof spec.defaultProps === 'object') {
        try {
          inst.setProperties(spec.defaultProps);
        } catch (err) {
          console.warn(`setProperties on ${spec.component} instance:`, err && err.message ? err.message : err);
        }
      }
      slotFrame.appendChild(inst);
    }
    c.appendChild(slotFrame);
  }

  figma.currentPage.appendChild(c);
  return { component: c, slots: { leading: null, trailing: null, center: null, label: null }, propKeys: {} };
}
